---
title: "ridgereg"
author: "Chathuranga Silva, Mohammed Bakheet, and Nikodimos Gezahegn"
date: "27th October 2019"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ridgereg}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(RBonusLab)
library(caret)
library(mlbench)
library(ggplot2)
```
## Using BostonHousing data
```{r BostonHousing}
data("BostonHousing")
housing <- BostonHousing
str(housing)
summary(housing)
```
## Data Cleaning
```{r BostonHousing2}
library("Amelia")
#Check for any NA’s in the dataframe.
missmap(housing,col=c('yellow','black'),y.at=1,y.labels='',legend=TRUE)

```
## Data Visualization with CorrPlots
```{r Visualization}
library("corrplot")
library("dplyr")
corrplot(cor(select(housing,-chas)))
```

```{r BostonHousingNext}

partitioining <- createDataPartition(
  y = BostonHousing$zn,
  ## the outcome data are needed
  p = .75,
  ## The percentage of data in the
  ## training set
  list = FALSE
)
#Spliting BostonHousing data into training and testing datasets
training <- BostonHousing[ partitioining,]
testing  <- BostonHousing[-partitioining,]
nrow(training)
nrow(testing)

```
## How to use ridgereg function
```{r ridgereg}
data("iris")
ridgereg(Petal.Length ~ Sepal.Width + Sepal.Length,data = iris)
```
## using caret package
```{r caret}
data(Sonar)

set.seed(107)
inTrain <- createDataPartition(
  y = Sonar$Class,
  ## the outcome data are needed
  p = .75,
  ## The percentage of data in the
  ## training set
  list = FALSE
)
## The format of the results

## The output is a set of integers for the rows of Sonar
## that belong in the training set.
str(inTrain)
## Spliting data into training and testing
training <- Sonar[ inTrain,]
testing  <- Sonar[-inTrain,]
nrow(training)
nrow(testing)

## Training the model
# plsFit <- train(
#   Class ~ .,
#   data = training,
#   method = "pls",
#   preProc = c("center", "scale"),
#   ## added:
#   tuneLength = 15
# )
```
